root: macros version has to be explicitly set for publish to work (#178)
Error:
10:56:14 [  0] → cargo publish --dry-run
    Updating crates.io index
error: failed to verify manifest at `/home/stuart.poole@canonical.com/source/canonical/fpgad/daemon/Cargo.toml`

Caused by:
  all dependencies must have a version requirement specified when publishing.
  dependency `fpgad_macros` does not specify a version
  Note: The published dependency will use the version from crates.io,
  the `path` specification will be removed from the dependency declaration.

Signed-off-by: Artie Poole <stuart.poole@canonical.com>